describe('template spec', () => {
  it('test de login valido', () => {
    cy.visit('https://the-internet.herokuapp.com/')
    cy.get(':nth-child(21) > a').click()
    cy.get('#username').type('tomsmith')
    cy.get('#password').type('SuperSecretPassword!')
    cy.get('.radius').click() 
    cy.get('.subheader').contains('Welcome to the Secure Area. When you are done click logout below.')   
  })
  it('test de login usuario invalido', () => {
    cy.visit('https://the-internet.herokuapp.com/')
    cy.get(':nth-child(21) > a').click()
    cy.get('#username').type('anac')
    cy.get('#password').type('SuperSecretPassword!')
    cy.get('.radius').click() 
    cy.get('#flash').contains('Your username is invalid!')  
  })  
  it('test de login contraseña invalida', () => {
    cy.visit('https://the-internet.herokuapp.com/')
    cy.get(':nth-child(21) > a').click()
    cy.get('#username').type('tomsmith')
    cy.get('#password').type('Password')
    cy.get('.radius').click() 
    cy.get('#flash').contains('Your password is invalid!') 
  })  
  it('test de login usuario y contraseña vacíos', () => {
    cy.visit('https://the-internet.herokuapp.com/')
    cy.get(':nth-child(21) > a').click()
    cy.get('#username').type('     ')
    cy.get('#password').type('     ')
    cy.get('.radius').click() 
    cy.get('#flash').contains('Your username is invalid!') 
  })    
  })